image:
  file: .gitpod.dockerfile
tasks:
  - init: cargo test
  - command: cargo watch -x check
    openMode: split-right
ports:
  - port: 5090
    onOpen: ignore
  - port: 6080
    onOpen: open-preview